INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 1 test', 'description 1', '30', '45', '2022-04-21 23:14:03.635', '2022-04-21 23:14:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 2 test', 'description 2', '20', '20', '2022-04-22 23:14:03.635', '2022-04-22 23:14:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 3 test', 'description 3', '10', '10', '2022-04-23 23:14:03.635', '2022-04-23 23:14:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 4 test', 'description 4', '40', '55', '2022-04-24 11:14:03.635', '2022-04-24 11:14:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 5 test', 'description 5', '80', '80', '2022-04-25 13:11:03.635', '2022-04-25 13:12:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 6 test', 'description 6',  '5', '10', '2022-04-26 14:13:03.635', '2022-04-26 14:14:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 7 test', 'description 7', '60', '75', '2022-04-27 15:15:03.635', '2022-04-27 15:16:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 8 test', 'description 8', '20', '15', '2022-04-28 17:17:03.635', '2022-04-28 17:18:03.636');
INSERT INTO gift_certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (default, 'name 9 test', 'description 9', '10',  '8', '2022-04-29 19:19:03.635', '2022-04-29 19:20:03.636');
INSERT INTO tag (id, name) VALUES (default, 'Tag 1 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 2 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 3 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 4 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 5 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 6 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 7 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 8 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 9 test');
INSERT INTO tag (id, name) VALUES (default, 'Tag 10 test');

INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('1', '1');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('1', '2');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('1', '3');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('2', '2');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('2', '3');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('3', '1');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('3', '4');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('3', '5');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('4', '6');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('4', '7');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('4', '8');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('5', '9');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('5', '10');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('6', '1');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('6', '2');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('6', '3');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('7', '4');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('7', '5');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('7', '6');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('8', '7');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('8', '8');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('9', '9');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('9', '10');
INSERT INTO gift_certificate_tag (gift_certificate_id, tag_id) VALUES ('9', '1');